name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant chmod to make gradlew executable
      run: chmod +x gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        
    - name: Docker build
      run: |
        docker login -u ${{ secrets.DOCERHUB_ID }} -p ${{ secrets.DOCKER_PWD }}
        docker build -t ${{secrets.DOCERHUB_ID}}/${{secrets.IMAGENAME}}:latest .
        docker push ${{secrets.DOCERHUB_ID}}/${{secrets.IMAGENAME}}:latest

    # - name: Deploy
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.PRIVATE_KEY }}
    #     script: |
    #       docker pull ${{secrets.DOCERHUB_ID}}/${{secrets.IMAGENAME}}:latest
    #       docker stop server
    #       docker run -d --rm --name server -p 8080:8080 growth123/test
